CSVファイルをJSONファイルに変換する関数、JSONファイルをCSVファイルに変換する関数の追加
kai-takuto/csv-json-convert pull request #4
Opened 2024-07-23 08:53 UTC by kai-takuto

ー内容ー
・関数：convert_csv_to_jsonの追加
　→csvからjsonの変換をすることができる関数
・関数：convert_json_to_csvの追加
　→jsonからcsvの変換をすることができる関数
ー仕様確認手順ー
・関数：check_file_existでファイルが存在するかを確かめる。
　→存在しなかった場合は、閉じる
　→存在した場合は、実行することができる
ー工程内容ー
1.csvファイルを読み込み処理をした後に、データに格納する
2.関数を作成し、工程１のコードを入れて、格納したデータをjsonファイルに変換して書き出すようにする
3.上の２つの工程をjson版で作成する　
4.CSVファイルをJSONファイルに変換する関数、JSONファイルをCSVファイルに変換する関数の追加 (現在地)
5.コマンドライン引数を受け取れるようにして、実行できるようにする
ー次の工程ー
コマンドライン引数を受け取れるようにして、実行できるようにする

2024-07-23 09:01 UTC, sugawarayss requested changes
コメントしました。
あと、ファイルの中身なんですが、 値について何も処理を入れていないですが、

CSV→JSON時には: NAの値を nullに
JSON→CSV時には null を "NA"に

してあげたほうが使い勝手が高まるような気がするんですがどう思いますか?

2024-07-23 09:01 UTC, sugawarayss commented on convert-project.py
> +    data: list[dict] = list(csv_data)
せっかくGenerator にしたのに、listにキャストしたらおいしいポイント潰しちゃっています。。。

2024-07-23 09:28 UTC, kai-takuto commented on convert-project.py
> +    data: list[dict] = list(csv_data)
申し訳ありません。「CSV→JSON時には: NAの値を nullに
JSON→CSV時には null を "NA"に」のお話について勉強不足で、理解できませんでした。

型ヒントの部分は「data: Generator[dict, None, None] = csv_data」に変更しました。
write_data_to_json関数の変数の型ヒントもデータ型がlist[dict]のままだったので、Generatorn[dict, None, None]に変更しました。

2024-07-23 11:15 UTC, waku1123 commented on convert-project.py
> +    data: list[dict] = list(csv_data)
ヒントの話ではないです。
Generator と listの違いをちゃんと理解してください。
ここでlistにキャストしてしまったら、ここで全部メモリに載ってしまうので、`read_csv_to_list` を Generator で返すように実装した意味がなくなってしまうという指摘です。

2024-07-23 11:22 UTC, sugawarayss commented on convert-project.py
> +    data: list[dict] = list(csv_data)
ヒントの話ではないです。。。

Generator と listの違いをちゃんと理解しましょう。
ここでlistにキャストしてしまったら、ここで全部メモリに載ってしまうので、read_csv_to_list を Generator で返すように実装した意味がなくなってしまうという指摘です。

2024-07-25 06:16 UTC, sugawarayss requested changes
json をCSVにできないように見えます

2024-07-25 06:16 UTC, sugawarayss commented on convert-project.py
> +            first_row = True
フラグでヘッダ行か判定するのでは無く、
`enumerate()` を使って、ループカウンタを一緒に取得するようにすればスマートです。

2024-07-29 01:43 UTC, sugawarayss requested changes
コメントしましたー

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        raise ValueError(f"File path '{input_file_path}' does not have extension '.csv' or '.json'.")
- 文字列はダブルクォートで統一しましょう。
- 21行目で チェック済なので、このelse分岐は不要だと思います。

私ならこう書きます。
```suggestion
    is_csv = True if input_file_path.suffix.lower() == ".csv" else False
    # または
    is_csv = input_file_path.suffix.lower() == ".csv"
```

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +    :param as_csv: csvファイル
`csvファイル` だけだと その引数が`何を示す`のかわかりづらいと思います。
もうちょっと情報を込めたコメントにしましょう

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +                csv_rows = {key: convert_row_data(value, as_json=as_csv) for key, value in row.items()}
csv → json の時と json → csv の時で データ変換のタイミングが異なるのは何故でしょうか?

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        with open(path, mode='r', encoding='utf-8') as csv_file:
文字列はダブルクォート

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        with open(path, mode='r', encoding='utf-8') as json_file:
文字列はダブルクォート

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        with open(output_path, mode='w', encoding='utf-8') as json_file:
文字列はダブルクォート

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        with open(output_path, mode='w', newline='', encoding='utf-8') as csv_file:
文字列はダブルクォート

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        if value.strip() == '' or value.strip().upper() == 'NA':
文字列はダブルクォート

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +            return 'NA'
文字列はダブルクォート

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +                json_rows = json.loads(json_rows)
わざわざjson を一度文字列化している理由は何でしょうか?

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +            writer.writerow({key: convert_row_data(value, as_json=False) for key, value in first_row.items()})
1行目だけ手書きで処理している理由は何でしょうか?
enumerate 使えば不要になりませんか?

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +    :param as_json: Trueの時にcsv-jsonに変換、Falseの時にjson-csvに変換
この関数の処理は csv か json か というのは関連が無いように見えるので、引数名が適切じゃないように思います。

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        return value
`as_json` が False だったら、 
- None → "NA"

しかしていないように思いますが、int にキャストした値は元に戻さなくて良いですか?

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +    文字列・数値・NAの変換を行う関数
変換対象を 文字列・数値・NA に限定した根拠は何でしょうか? 
それと、どう変換するのか? をここに書いてあげたようが親切な気がします

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +    :param as_json: jsonファイル
`as_json: jsonファイル` だとその引数が何を示すのかわかりづらいと思います。
もうちょっと情報を込めたコメントにしましょう

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +    :param to_json:jsonファイル
`to_json: jsonファイル` だとその引数が何を示すのかわかりづらいと思います。
もうちょっと情報を込めたコメントにしましょう

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        print("Usage: python convert.py <file_path>")
csv を変換した時と表示内容が異なる理由は何でしょうか

2024-07-29 01:43 UTC, sugawarayss commented on convert-project.py
> +        write_file(data_generator, output_path=csv_file_path, as_json=False)
csv変換の時とほぼ同じ処理なので、もっとスッキリ書けそうな気がします。

2024-07-29 01:54 UTC, sugawarayss requested changes
追加コメントしましたー

2024-07-29 01:54 UTC, sugawarayss commented on convert-project.py
> +def convert_row_data(value, as_json: True) -> Any:
型ヒント `Any` は `何か戻り値がある` というくらいの意味しかないです。
つまり 型ヒントを使うメリットが薄いのでもう少し厳密なヒントにしましょう。
typing.Union や typing.Optional を使ってみましょう

2024-07-29 01:54 UTC, sugawarayss commented on convert-project.py
> +def convert_file(file_path: Path, to_json: bool = True):
戻り値を返さないなら 型ヒントは `-> None:` としましょう

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        raise ValueError(f"File path '{input_file_path}' does not have extension '.csv' or '.json'.")
承知しました。
28行目の部分を削除し、「is_csv = True if input_file_path.suffix.lower() == ".csv" else False」に変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +    :param as_csv: csvファイル
承知しました。
csvファイルから「変換したいファイル "csv=True/json=False" のbool値」に変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        with open(path, mode='r', encoding='utf-8') as csv_file:
承知しました。
申し訳ありません。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +                csv_rows = {key: convert_row_data(value, as_json=as_csv) for key, value in row.items()}
csv → json の時と json → csv の時のデータ変換のタイミングが異なる理由は、同じにしようとした際に、うまく動作させることができなかったことが理由になります。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        with open(path, mode='r', encoding='utf-8') as json_file:
承知しました。
申し訳ありません。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +    :param as_json: jsonファイル
承知しました。
jsonファイルから「読み込んだファイル "csv = True / json = False" のbool値」に変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        with open(output_path, mode='w', encoding='utf-8') as json_file:
承知しました。
申し訳ありません。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        with open(output_path, mode='w', newline='', encoding='utf-8') as csv_file:
承知しました。
申し訳ありません。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +def convert_row_data(value, as_json: True) -> Any:
承知しました。
AnyからUnion[str, int, None]に変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +    文字列・数値・NAの変換を行う関数
変換対象を文字列・数値・NAに限定した根拠は、input.csvのデータを見て３つの方しかないと思い、限定しました。
承知しました。
文字列・数値・NAの変換を行う関数から「"文字列 -> str / 数値 -> int / NA -> null"に変換を行う関数」に変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +    :param as_json: Trueの時にcsv-jsonに変換、Falseの時にjson-csvに変換
承知しました。
変数名：as_jsonから、変数名：row_dataに変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        if value.strip() == '' or value.strip().upper() == 'NA':
申し訳ありません。
承知しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +            return 'NA'
申し訳ありません。
承知しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        return value
申し訳ありません。
その部分は見落としていました。
intにキャストしたものを戻すコードを追加しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +def convert_file(file_path: Path, to_json: bool = True):
承知しました。
Noneに変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +    :param to_json:jsonファイル
承知しました。
jsonファイルから「変換するファイル"csv-json = True / json-csv = False"のbool値」に変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        print("Usage: python convert.py <file_path>")
申し訳ありません。
csvを変換したときの表示内容を、jsonを変換するときにも表示させようと考えていましたが、変更し忘れていました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +                json_rows = json.loads(json_rows)
何も考えずに使用していました。
今考えると必要ないと感じたので、削除しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +            writer.writerow({key: convert_row_data(value, as_json=False) for key, value in first_row.items()})
enumerate()のご指摘があったことを忘れていました。
enumerate()を使用してヘッダーと一緒に取得するように変更しました。

2024-07-29 06:57 UTC, kai-takuto commented on convert-project.py
> +        write_file(data_generator, output_path=csv_file_path, as_json=False)
承知しました。
elseを消して、連結させました。

2024-07-29 07:13 UTC, sugawarayss commented on convert-project.py
> +            for header, row in enumerate(row_generator):
enumerateは __next__() を実装していて tuple[int, Any] を返します。
なので int としてループカウンタとして使えるようになっています。

なので 値が意味するのは `header` かどうかではないので、変数名は変えたほうが良いですね。(使用箇所の64行目の header == 0 が意味がとおりづらい)

2024-07-29 07:13 UTC, sugawarayss commented on convert-project.py
> +    :param as_json: Trueの時にcsv-jsonに変換、Falseの時にjson-csvに変換
row_data では 意味がよりわかりづらくなってしまいますね。もうちょっと考えてみてください。

2024-07-29 07:16 UTC, sugawarayss commented on convert-project.py
> +    :param as_json: jsonファイル
んーイマイチな感じがします(直感的に掴みづらい感ある) が、さほど重要ではないのでよしとします

2024-07-29 07:16 UTC, sugawarayss commented on convert-project.py
> +    :param to_json:jsonファイル
ここもイマイチな感じですが、同様によしとします

2024-07-29 07:18 UTC, sugawarayss commented on convert-project.py
> +        print("Usage: python convert.py <file_path>")
表示文言が間違っていませんか?

2024-07-29 07:18 UTC, sugawarayss commented on convert-project.py
> +        write_file(data_generator, output_path=csv_file_path, as_json=False)
これでは、CSVを変換し終わったあとにJson2CSV を実行しちゃいませんか?

2024-07-29 07:19 UTC, sugawarayss requested changes
おしい

2024-07-29 07:21 UTC, kai-takuto commented on convert-project.py
> +        write_file(data_generator, output_path=csv_file_path, as_json=False)
申し訳ありません。
２つのファイルが同時に作成されるようになっていました。元に戻すように変更します。

2024-07-29 07:52 UTC, kai-takuto commented on convert-project.py
> +            for header, row in enumerate(row_generator):
承知しました。
変数headerから変数first_rowに変更しました。

2024-07-29 08:53 UTC, kai-takuto commented on convert-project.py
> +            for header, row in enumerate(row_generator):
変数名をheaderからkeyに変更しました。

2024-07-29 09:31 UTC, sugawarayss requested changes
もうちょい

2024-07-29 09:31 UTC, sugawarayss commented on convert-project.py
> +    output_file_path = "output.json" if to_json else "output.csv"
私なら↓書きますね

```suggestion
    output_file_path = f"output.{'json' if to_json else 'csv'}"
```

2024-07-29 09:31 UTC, sugawarayss commented on convert-project.py
> +    if row_data:
`row_data` は名前がイマイチなので変えましょう

2024-07-29 10:14 UTC, kai-takuto commented on convert-project.py
> +    if row_data:
名前をcsv_flagに変更しました。
またvalueの型ヒントをstr型にしました。

2024-07-29 10:14 UTC, kai-takuto commented on convert-project.py
> +    output_file_path = "output.json" if to_json else "output.csv"
承知しました。変更しました。

2024-07-30 00:14 UTC, sugawarayss requested changes

2024-07-30 00:14 UTC, sugawarayss commented on convert-project.py
> -        raise ValueError(f"File path '{input_file_path}' does not have extension '.csv' or '.json'.")
ここは消さないでください。

このチェックを消してしまうと、ファイル名に csv または json 以外も通してしまいます。

2024-07-30 02:22 UTC, kai-takuto commented on convert-project.py
> +    if row_data:
承知しました。
csv_flagに変更しました。

2024-07-30 02:22 UTC, kai-takuto commented on convert-project.py
> +    output_file_path = "output.json" if to_json else "output.csv"
承知しました。
ありがとうございます。

2024-07-30 02:24 UTC, kai-takuto commented on convert-project.py
> -        raise ValueError(f"File path '{input_file_path}' does not have extension '.csv' or '.json'.")
承知しました。
元に戻しました。

2024-07-30 02:49 UTC, kai-takuto commented
型ヒントの根拠：
<img width="1920" alt="スクリーンショット 2024-07-30 11 44 08" src="https://github.com/user-attachments/assets/9448365d-483b-40fb-97e2-39df70ee6c67">

input.csvとoutput.csvの差異チェック(差異がない時)：
<img width="1920" alt="スクリーンショット 2024-07-30 11 47 01" src="https://github.com/user-attachments/assets/7416a51d-7efb-4a16-af94-41f9fe9cdcd0">

input.csvとoutput.csvの差異チェック(差異がある時)：
<img width="1920" alt="スクリーンショット 2024-07-30 11 48 13" src="https://github.com/user-attachments/assets/2b3e8acf-9ea6-4cfa-b5b7-be3b21cc76e5">

2024-07-30 02:59 UTC, sugawarayss commented
- データ内容の仕分けについては、各種の内訳はだせませんか?(具体的にどういった値が含まれるのか)
    - 「数を数えました」だけだとほんとに?ってなりません?  
- 差分のチェックはdiff コマンドを使わず実装した理由は何でしょう?

2024-09-12 03:45 UTC, kai-takuto commented
以前まではinput.csvとoutput.csvのファイル形式が異なっていることから差分が出ていることが確認できました。
input.csvのファイル形式をCRLFに戻して変換作業を行い、差分が出ないことを確認いたしましたのでご確認よろしくお願いいたします。
![スクリーンショット 2024-09-12 2 32 35](https://github.com/user-attachments/assets/a905142b-9b2c-4360-b1f5-6a5b53fb49d9)

2024-09-13 09:35 UTC, sugawarayss approved these changes
LGTM

2024-09-13 09:58 UTC, merged